databases:
  - name: bubble_development
    databaseName: bubble_development
    user: bubble_development_user

services:
  - type: web
    name: bubble_marketplace
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bubble_development
          property: connectionString
      - key: MASTER_KEY
        sync: false
